// LOADOUTS //
SCAV_PRIMARIES = ["rhs_weap_ak74","brf_akm_worn","rhs_weap_akmn","rhs_weap_aks74","rhs_weap_aks74u","rhs_weap_asval","hlc_rifle_L1A1SLR","hlc_rifle_LAR","UK3CB_FNFAL_FULL","hlc_rifle_FN3011Modern","rhs_weap_Izh18","rhs_weap_kar98k","sgun_HunterShotgun_01_F","sgun_HunterShotgun_01_sawedoff_F","rhs_weap_l1a1_wood","UK3CB_Enfield","hlc_rifle_SLR","rhs_weap_m1garand_sa43","rhs_weap_m14","hlc_rifle_M1903A1","rhs_weap_m24sws","m14_762","rhs_weap_m3a1","rhs_weap_M590_8RD","rhs_weap_M590_5RD","rhs_weap_m76","rhs_weap_scorpion","rhs_weap_m92","rhs_weap_m38","rhs_weap_MP44","rhs_weap_pm63","rhs_weap_pp2000","rhs_weap_savz61","hlc_rifle_saiga12k","hlc_rifle_amt","UK3CB_SVD_OLD","rhs_weap_vss","UK3CB_M16A1","hlc_wp_xm4"];
SCAV_SECONDARIES = ["rhs_weap_6p53","rhs_weap_pb_6p9","UK3CB_BHP","rhs_weap_cz99","rhsusf_weap_glock17g4","hlc_Pistol_M11","rhsusf_weap_m1911a1","rhsusf_weap_m9","hgun_Pistol_01_F","hgun_Rook40_F","rhs_weap_pya","hlc_pistol_Mk25","hgun_P07_blk_F","rhs_weap_makarov_pm","hlc_pistol_P239","hlc_Pistol_P228","hlc_pistol_P226WestGerman","hlc_Pistol_M11A1","hlc_pistol_P226US","hlc_pistol_P229R","rhs_weap_tt33"];
SCAV_CLOTHING = ["LOP_U_CHR_Woodlander_06","LOP_U_CHR_Woodlander_05","LOP_U_CHR_Woodlander_04","LOP_U_CHR_Woodlander_03","LOP_U_CHR_Woodlander_02","LOP_U_CHR_Woodlander_01","UK3CB_CHC_C_U_COACH_05","UK3CB_CHC_C_U_COACH_02","UK3CB_CHC_C_U_COACH_03","UK3CB_CHC_C_U_COACH_01","UK3CB_CHC_C_U_COACH_04","UK3CB_ADE_O_U_06_F","UK3CB_ADE_O_U_06_E","UK3CB_ADE_O_U_06_D","UK3CB_ADE_O_U_06_C","UK3CB_ADE_O_U_06_B","UK3CB_ADE_O_U_06","UK3CB_ADC_C_Hunter_U_07","UK3CB_ADC_C_Hunter_U_09","UK3CB_ADC_C_Hunter_U_08","UK3CB_ADC_C_Hunter_U_10","UK3CB_ADC_C_Hunter_U_06","UK3CB_TKM_B_U_06_C","UK3CB_TKM_B_U_06_B","UK3CB_TKM_B_U_06","UK3CB_TKM_I_U_06_C","UK3CB_TKM_I_U_06_B","UK3CB_TKM_I_U_06","UK3CB_ADE_O_U_04_F","UK3CB_ADE_O_U_04_D","UK3CB_ADE_O_U_04_E","UK3CB_ADE_O_U_04_C","UK3CB_ADE_O_U_04_B","UK3CB_ADE_O_U_04","UK3CB_TKP_B_U_CombatUniform_TAN","UK3CB_ADC_C_Hunter_U_05","UK3CB_ADC_C_Hunter_U_01","UK3CB_ADC_C_Hunter_U_03","UK3CB_ADC_C_Hunter_U_04","UK3CB_ADC_C_Hunter_U_02","U_C_HunterBody_grn","U_C_E_LooterJacket_01_F"];
SCAV_HELMETS = ["LOP_H_Beanie_tan","LOP_H_Beanie_mtp","LOP_H_Beanie_digit","LOP_H_Beanie_marpat","LOP_H_Beanie_multicam","LOP_H_Beanie_dpmw","LOP_H_Beanie_flec","LOP_H_Beanie_m81","UK3CB_H_Shemag_white","UK3CB_H_Shemag_tan","UK3CB_H_Shemag_red","UK3CB_H_Shemag_oli","UK3CB_H_Shemag_grey","UK3CB_H_Shemag_blk","brf_fieldcap_ardistan_desert","FGN_FieldCap_Kamysh","brf_fieldcap_vsr_agr","rhs_fieldcap_digi","rhs_fieldcap_digi2","rhs_fieldcap_izlom","rhs_fieldcap_ml","rhs_fieldcap_khk","rhs_fieldcap_vsr","UK3CB_CW_SOV_O_EARLY_H_FieldCap_KHK","rhsgref_patrolcap_specter","LOP_H_Fieldcap_UKR","LOP_H_Fieldcap_CDF","LOP_H_Fieldcap_BLU","rhs_fieldcap","rhs_ssh68","LOP_H_SSh68Helmet_TAN","LOP_H_SSh68Helmet_OLV","LOP_H_SSh68Helmet_BLK","UK3CB_H_Ushanka_Cap_01","LOP_H_Ushanka","rhs_6b27m_green","rhs_altyn_novisor","rhssaf_bandana_digital","rhssaf_bandana_digital_desert","rhssaf_bandana_md2camo","rhssaf_bandana_oakleaf","rhssaf_bandana_smb","H_Bandanna_gry","H_Bandanna_blu","H_Bandanna_khk","H_Bandanna_sgg","H_Bandanna_camo","H_Bandanna_surfer","H_Bandanna_sand","H_Bandanna_cbr","H_Bandanna_khk_hs","H_Bandanna_mcamo","H_PASGT_basic_olive_F","usm_bdu_boonie_tgrstp","usm_bdu_boonie_blk","usm_bdu_boonie_blu","usm_bdu_boonie_des","usm_bdu_boonie_erdl","usm_bdu_boonie_odg","usm_bdu_boonie_gry","usm_bdu_boonie_tan","usm_bdu_boonie_wdl","usm_bdu_cap_blk","usm_bdu_cap_blu","usm_bdu_cap_des","usm_bdu_cap_gry","usm_bdu_cap_odg","usm_bdu_cap_tan","usm_bdu_cap_wdl","H_Cap_blk","H_Cap_grn","H_Cap_oli","H_Cap_red","H_Cap_tan","H_Cap_blk_Raven","usm_headwrap_tgrstp","usm_headwrap_tan","usm_headwrap_odg1","usm_headwrap_des","usm_headwrap_dcu","usm_headwrap_odg2","usm_headwrap_blk","rhssaf_helmet_m97_olive_nocamo"];
SCAV_VESTS = ["LOP_V_Chestrig_VSR","LOP_V_Chestrig_Kamysh","LOP_V_Chestrig_Black","LOP_V_6B23_OLV","LOP_V_6B23_6Sh92_OLV","UK3CB_TKA_I_V_6Sh92_Oli","UK3CB_TKP_I_V_6Sh92_Blk","LOP_V_6Sh92_OLV","rhs_6b23_6sh116_od","rhs_6b23","FGN_RU_6B513_Khaki","FGN_RU_6B513","rhs_6b5_khaki","UK3CB_V_CW_Chestrig_2_Small","UK3CB_V_CW_Chestrig","rhsgref_alice_webbing","UK3CB_V_Belt_Rig_Lite_KHK","UK3CB_V_Belt_Rig_KHK","UK3CB_V_Belt_KHK","rhsgref_chicom_m88","rhsgref_chicom","brf_chicom_desert_m88","brf_chicom_desert","brf_chicom_brown_m88","brf_chicom_brown","brf_chestrig_khaki","brf_chestrig_black","rhsgref_chestrig","brf_chestrig_green","V_SmershVest_01_F","UK3CB_V_Chestrig_Lite_2_Small_KHK","UK3CB_V_Chestrig_Lite_KHK","UK3CB_V_Chestrig_TKA_BRUSH","UK3CB_V_Chestrig_2_Small_OLI","UK3CB_V_Chestrig_TKA_OLI","UK3CB_V_Chestrig_WDL_01","UK3CB_V_Chestrig_WDL_02","UK3CB_V_Chestrig_Tan","UK3CB_V_Chestrig_ERDL","UK3CB_V_Chestrig_OLI","rhssaf_vest_md12_digital","rhssaf_vest_md12_digital_desert","rhssaf_vest_md12_m70_rifleman","rhssaf_vest_md98_digital","rhssaf_vest_md98_md2camo","brf_md98_tan","brf_md98_tan_rifleman","rhssaf_vest_md98_woodland","rhssaf_vest_md98_rifleman","rhssaf_vest_md99_digital_rifleman","rhssaf_vest_md99_md2camo","rhssaf_vest_md99_md2camo_rifleman","rhssaf_vest_md99_woodland","rhssaf_vest_md99_woodland_rifleman","V_BandollierB_oli","V_BandollierB_khk","V_BandollierB_rgr","V_BandollierB_cbr","V_BandollierB_blk","V_TacChestrig_cbr_F","V_TacChestrig_grn_F","V_TacChestrig_oli_F","rhs_vydra_3m","brf_vydra_olive","brf_vydra_tan","UK3CB_TKA_I_V_vydra_3m_TKA_Brush","UK3CB_TKA_I_V_vydra_3m_Tan","V_TacVest_blk","V_TacVest_brn","V_TacVest_camo","UK3CB_AAF_B_V_TacVest_DIGI_BLK","UK3CB_ADA_B_V_TacVest_DPM","V_TacVest_khk","V_TacVest_oli","V_I_G_resistanceLeader_F","FGN_CauR_Tactical_Vest_M81","UK3CB_TKA_B_V_TacVest_Tan","FGN_CauR_Tactical_Vest_Black_Rifleman","FGN_CauR_Tactical_Vest_3Color_Rifleman","FGN_CauR_Tactical_Vest_Khaki_Rifleman","FGN_CauR_Tactical_Vest_M81_Rifleman"];
SCAV_BACKPACKS = ["UK3CB_B_Alice_Bedroll_K","UK3CB_B_Alice_K","usm_pack_alice","UK3CB_UN_B_B_RIF","UK3CB_CHC_C_B_HIKER","brf_bag_desert","brf_bag_olive","UK3CB_B_Bedroll_Backpack","B_AssaultPack_blk","UK3CB_ADA_B_B_ASS","B_AssaultPack_dgtl","B_AssaultPack_rgr","B_AssaultPack_khk","B_AssaultPack_wdl_F","UK3CB_TKA_B_B_ASS","B_Carryall_cbr","UK3CB_AAF_B_B_CARRYALL_DIGI_GRN","B_Carryall_green_F","B_Carryall_oli","B_FieldPack_oli","B_FieldPack_green_F","B_FieldPack_taiga_F","B_FieldPack_blk","B_FieldPack_cbr","UK3CB_AAF_B_B_FIELDPACK_DIGI_GRN","rhssaf_kitbag_smb","B_Kitbag_rgr","B_Kitbag_cbr","UK3CB_CW_US_B_LATE_B_RIF_04","B_Kitbag_tan","UK3CB_UN_B_B_ASS","UK3CB_CPD_B_B_ASS_BLU","UK3CB_TKP_O_B_ASS_BLK","rhs_medic_bag","brf_bagmedic_desert","brf_bagmedic_olive","B_Messenger_Olive_F","B_Messenger_Gray_F","B_Messenger_Coyote_F","B_Messenger_Black_F","rhs_rpg_empty","brf_sidor_olive","brf_sidor_desert","rhs_sidor","LOP_AM_FalconII_Enfield","LOP_US_Sidor_SVD","UK3CB_CW_SOV_O_EARLY_B_Sidor_RIF","UK3CB_CW_SOV_O_LATE_B_Sidor_RIF","rhs_assault_umbts","brf_umbts_desert","rhs_assault_umbts_engineer_empty","brf_umbts_engineer_olive","brf_umbts_olive","UK3CB_TKA_O_B_RIF_Khk","UK3CB_TKA_O_B_ENG_Tan","UK3CB_TKA_O_B_RIF_Tan","UK3CB_TKA_O_B_ENG_Khk","B_TacticalPack_oli","B_TacticalPack_rgr","B_TacticalPack_blk","B_TacticalPack_mcamo"];
SCAV_FACE = ["G_AirPurifyingRespirator_02_black_F","G_AirPurifyingRespirator_02_olive_F","G_AirPurifyingRespirator_02_sand_F","G_AirPurifyingRespirator_01_F","G_Aviator","rhs_balaclava","UK3CB_G_Balaclava","G_Balaclava_blk","G_Balaclava_lowprofile","G_Balaclava_combat","rhs_balaclava1_olive","rhs_googles_black","UK3CB_G_Balaclava_Neck_Shemag","G_Balaclava_oli","G_Bandanna_tan","dvk_shemag_tan_altcsat","G_Bandanna_sport","G_Bandanna_shades","dvk_tacg_shem_w_altcsat","dvk_tacg_o_shem_altcsat","dvk_tacg_shem_altcsat","G_Bandanna_oli","G_Bandanna_khk","G_Bandanna_beast","G_Bandanna_blk","G_Bandanna_aviator","rhs_googles_yellow","rhs_ess_black","rhs_googles_orange","rhs_googles_clear","G_Combat","G_Combat_Goggles_tna_F","usm_kneepads_blk","usm_kneepads_safariland","UK3CB_G_Face_Wrap_01","G_Lowprofile","UK3CB_G_Neck_Shemag_Tan","UK3CB_G_Neck_Shemag","UK3CB_G_Neck_Shemag_Oli","dvk_altcsat_low_tan","G_Respirator_blue_F","G_Respirator_white_F","G_Respirator_yellow_F","G_EyeProtectors_F","G_EyeProtectors_Earpiece_F","rhs_scarf","G_Shades_Black","G_Shades_Green","G_Shades_Blue","G_Shades_Red","rhsusf_shemagh_od","rhsusf_shemagh2_grn","FGN_CauR_Shemag_green","rhsusf_shemagh_grn","FGN_CauR_Shemag_brown","FGN_CauR_Shemag","rhsusf_shemagh2_od","rhsusf_shemagh2_tan","rhsusf_shemagh2_white","rhsusf_shemagh_gogg_grn","rhsusf_shemagh2_gogg_grn","rhsusf_shemagh2_gogg_od","rhsusf_shemagh_gogg_tan","rhsusf_shemagh2_gogg_tan","dvk_shemag_w_altcsat","rhsusf_shemagh_white","dvk_shemag_altcsat","rhsusf_shemagh_tan","rhsusf_shemagh_gogg_od","G_Squares","rhsusf_oakley_goggles_ylw","rhsusf_oakley_goggles_clr","rhsusf_oakley_goggles_blk","rhsusf_shemagh_gogg_white","rhsusf_shemagh2_gogg_white","usm_swdgoggles","usm_gigloves","dvk_tacg_altcsat","G_Tactical_Clear","G_Tactical_Black","dvk_tacg_o_altcsat","usm_scarf2","usm_scarf","usm_giglovesscarf","usm_giglovesscarf2"];

// UNIT SPAWNING //
USED_UNITS = ["rhsgref_ins_g_rifleman_akm", "rhsgref_ins_g_machinegunner", "rhsgref_ins_g_squadleader"];
CONVERT_EDEN_UNITS = paramsArray select 0;
HEAVY_CHANCE = 5; //percentage, default 5





